#*******Method 1******
Output:
	g++ main.cpp add.cpp greeting.cpp -o Output

#*******Method 2******
# CP = g++
# Output:
# 	$(CP) main.cpp add.cpp greeting.cpp -o Output

# Clean:
# 	rm Output

#*******Method 3******
# CP = g++
# Output: main.o add.o greeting.o 
# 	$(CP) main.cpp add.cpp greeting.cpp -o Output

# main.o: main.cpp header.h
# 	$(CP) -c main.cpp

# add.o: add.cpp header.h
# 	$(CP) -c add.cpp



# Clean:
# 	rm *.o Output
