Output:
	g++ singleton_class.cpp singleton_main.cpp -o singleton

# CP = g++
# Output:
# 	$(CP) singleton_class.cpp singleton_main.cpp -o singleton

# Clean:
# 	rm singleton


# CP = g++
# Output: singleton_class.o singleton_main.o 
# 	$(CP) singleton_class.cpp singleton_main.cpp -o singleton

# main.o: singleton_main.cpp singleton.hpp
# 	$(CP) -c singleton_main.cpp 

# class.o: singleton_class.cpp singleton.hpp
# 	$(CP) -c singleton_class.cpp



# Clean:
# 	rm *.o singleton
